In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
investing_df= pd.read_csv('Crypto_Fund_List without emails.csv')
investing_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,Firm Name,Address,Address 2,City,State/Province,Zip,Country,Map,Code,Phone,...,SEC Registered?,# of Clients,# of Accounts,Change in # of Accounts % (12 mo.),Investments 1,Investments 2,Investments 3,Investments 4,Investments 5,Form of Incorporation
1,1confirmation,459 Hamilton Avenue,0,Palo Alto,CA,94123,United States,http://maps.google.com/maps?f=q&hl=en&geocode=...,1,650 838 4316,...,No,NaN,NaN,NaN,dyDx,Basecoin,MakerDao,0.0%,0.0%,NaN
2,360 Blockchain,"Suite 734, 1055 Dunsmuir Street",0,Vancouver,BC,V7X 1B1,Canada,http://maps.google.com/maps?f=q&hl=en&geocode=...,1,778 806 5150,...,No,NaN,NaN,NaN,Arcology,SV Cryptolab,Pressland,ePIC Blockchain Technologies,0.0%,NaN
3,3iQ,"4800-1 King Street West, Box 160",0,Toronto,ON,M5H 1A1,Canada,http://maps.google.com/maps?f=q&hl=en&geocode=...,1,416 639 2130,...,No,NaN,NaN,NaN,Ethereum,Bitcoin,Litecoin,0.0%,0.0%,NaN
4,8 Decimal Capital,2140 Columbia Street,0,Palo Alto,CA,94306,United States,http://maps.google.com/maps?f=q&hl=en&geocode=...,1,650 785 2534,...,No,NaN,NaN,NaN,Bluzelle,0.0%,0.0%,0.0%,0.0%,NaN